//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAA_Paper_Templates
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchPlayer
    {
        public int ID { get; set; }
        public string Goals { get; set; }
        public string Penalties { get; set; }
        public string Points { get; set; }
        public string Frees { get; set; }
        public string IsSubbed { get; set; }
        public string MinuteOn { get; set; }
        public string MinuteOff { get; set; }
        public string PlayerNumber { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Team Teams { get; set; }
        public virtual Player Player { get; set; }
    }
}
